In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('vgchartz-2024.csv')

df.shape

(64016, 14)

In [13]:
# df.info()

df.isna().sum()

img                 0
title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [16]:
df.head()

# df.tail()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [ ]:
# summary statistic for numeric columns
df.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [49]:
# find unique categories and spot potential typos
with pd.option_context('display.max_rows', None):
    display(df['genre'].value_counts())

genre
Misc                9304
Action              8557
Adventure           6260
Role-Playing        5721
Sports              5586
Shooter             5410
Platform            4001
Strategy            3685
Puzzle              3521
Racing              3425
Simulation          3158
Fighting            2367
Action-Adventure    1877
Visual Novel         493
Music                297
Party                151
MMO                  115
Education             35
Board Game            33
Sandbox               20
Name: count, dtype: int64

In [ ]:
# filtered_df = df[df['publisher'] == 'Unknown']

# filtered_df

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
595,/games/boxart/full_6721404JapanFrontccc.jpg,Gran Turismo Concept 2001 Tokyo,PS2,Racing,Unknown,Polyphony Digital,NaN,1.84,NaN,0.42,1.10,0.33,NaN,NaN
1948,/games/boxart/full_final-fantasy-type-0_861Jap...,Final Fantasy Type-0,PSP,Role-Playing,Unknown,Square Enix,NaN,0.81,NaN,0.81,NaN,NaN,2020-12-31,NaN
2305,/games/boxart/full_rift_95AmericaFront.jpg,RIFT,PC,Role-Playing,Unknown,Trion Worlds,8.3,0.70,0.47,NaN,0.16,0.08,2011-03-01,NaN
2447,/games/boxart/full_9579299JapanFrontccc.gif,Dragon Quest Monsters: Caravan Heart,GBA,Role-Playing,Unknown,TOSE,NaN,0.66,NaN,0.64,NaN,0.02,2020-12-31,NaN
2574,/games/boxart/8635280ccc.jpg,X-Man,2600,Action,Unknown,Universal Gamex,NaN,0.63,0.58,NaN,0.04,0.01,1983-01-01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63982,/games/boxart/full_6855581AmericaFrontccc.jpg,The Wreck,PC,Visual Novel,Unknown,The Pixel Hunt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-04-13
63983,/games/boxart/full_3646233AmericaFrontccc.jpg,The Wreck,PS4,Visual Novel,Unknown,The Pixel Hunt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-04-13
63984,/games/boxart/full_5400641AmericaFrontccc.jpg,The Wreck,PS5,Visual Novel,Unknown,The Pixel Hunt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-04-13
64003,/games/boxart/full_8639221AmericaFrontccc.jpg,Witch on the Holy Night,NS,Visual Novel,Unknown,Type-Moon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-05
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29

In [54]:
df = df.drop(columns=['img', 'last_update'])

KeyError: "['img', 'last_update'] not found in axis"

In [66]:
# 1. Define the columns that define a duplicate record
subset_cols = ['title', 'console', 'release_date']

# 2. Filter the dataframe to show only duplicate rows
duplicate_rows = df[df.duplicated(subset=subset_cols, keep=False)]

# 3. Sort by those columns so duplicate matches appear next to each other
duplicate_rows = duplicate_rows.sort_values(by=subset_cols)

# 4. Display the results
display(duplicate_rows)

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
55926,Ace Combat 5: The Unsung War,PS2,Simulation,Namco,Namco,NaN,NaN,NaN,NaN,NaN,NaN,2004-10-25
56164,Ace Combat 5: The Unsung War,PS2,Simulation,Namco,Project ACES,8.0,NaN,NaN,NaN,NaN,NaN,2004-10-25
13461,Akko ni Omakase! Brain Shock,DS,Misc,Taito,Taito,NaN,0.04,NaN,0.04,NaN,NaN,2006-12-07
13536,Akko ni Omakase! Brain Shock,DS,Misc,Taito,Taito Corporation,NaN,0.04,NaN,0.04,NaN,NaN,2006-12-07
18885,Aokana: Four Rhythm Across the Blue,NS,Visual Novel,Sprite,Sprite,NaN,0.00,NaN,0.00,NaN,NaN,2020-08-21
...,...,...,...,...,...,...,...,...,...,...,...,...
63266,Z,PC,Strategy,Virgin Interactive,Bitmap Brothers,NaN,NaN,NaN,NaN,NaN,NaN,1996-07-31
2438,Zaidan Houjin Nippon Kanji Nouryoku Kentei Kyo...,DS,Misc,IE Institute,IE Institute,NaN,0.66,NaN,0.66,NaN,NaN,2006-11-09
2439,Zaidan Houjin Nippon Kanji Nouryoku Kentei Kyo...,DS,Misc,IE Institute,IE Institute,NaN,0.66,NaN,0.66,NaN,NaN,2006-11-09
43231,bit Generations: Soundvoyager,GBA,Puzzle,Nintendo,skip Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27
43232,bit Generations: Soundvoyager,GBA,Puzzle,Nintendo,skip Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27

In [78]:
# 1. Sort by total_sales descending, pushing NaN values to the very end
df_sorted = df.sort_values(
    by='total_sales', 
    ascending=False, 
    na_position='last'
)

df = df_sorted.drop_duplicates(subset=['title', 'console', 'release_date'], keep='first')

In [79]:
df

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...
64011,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11
64012,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64013,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64014,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28
64015,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
# Standardize string columns
string_cols = ['title', 'publisher', 'developer', 'genre', 'console']
df[string_cols] = df[string_cols].apply(lambda col: col.str.strip())

# # Standardize in a single pipeline
# df['Clean_Company'] = (df['Company']
#                        .str.strip()               # Remove extra spaces on outer edges
#                        .str.lower()               # Enforce lower case for uniformity
#                        .str.replace(r'[^\w\s]', '', regex=True) # Strip punctuation
#                        .str.replace(r'\s+', ' ', regex=True))  # Collapse interior whitespace

df

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...
64011,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11
64012,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64013,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64014,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28
64015,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# datetime format
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

df

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...
64011,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11
64012,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64013,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64014,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28
64015,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [ ]:
# I'll just keep the NaN values empty in the numerical columns

In [90]:
# Returns a True/False series
mask = df['developer'] == 'Unknown'

# Returns the actual rows matching the condition
filtered_df = df[mask]
# filtered_df = df[df['developer'].isnull()]

filtered_df

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
391,Monopoly,PC,Misc,Hasbro Interactive,Unknown,NaN,2.39,1.49,NaN,0.81,0.10,1995-01-01
550,Destiny,X360,Misc,Activision,Unknown,NaN,1.94,1.32,NaN,0.44,0.19,2014-09-09
702,Disney Infinity,Wii,Misc,Disney Interactive Studios,Unknown,NaN,1.66,1.06,NaN,0.44,0.16,2013-08-18
787,Disney Infinity,X360,Misc,Disney Interactive Studios,Unknown,NaN,1.53,1.04,NaN,0.35,0.15,2013-08-18
955,Skylanders SWAP Force,X360,Platform,Activision,Unknown,NaN,1.36,0.88,NaN,0.35,0.13,2013-10-13
...,...,...,...,...,...,...,...,...,...,...,...,...
63170,War on Folvos,PC,Strategy,Lonely Troops,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,2006-09-26
63203,Warrior Chess,And,Strategy,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,2014-01-10
63519,Northgard,NS,Strategy,Shiro Games,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-26
63754,Wishmaster,PC,Visual Novel,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaT
63973,The Mind's Eclipse,PC,Visual Novel,Mind's Eclipse Interactive,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-25

In [91]:
df['developer'] = df['developer'].fillna('Unknown')

df

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...
64011,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11
64012,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64013,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30
64014,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28
64015,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [94]:
calculated_total = df[['na_sales', 'jp_sales', 'pal_sales', 'other_sales']].sum(axis=1)
# Highlight rows where total sales deviates from regional sum
sales_discrepancies = df[abs(df['total_sales'] - calculated_total) > 0.05]

sales_discrepancies

Empty DataFrame
Columns: [title, console, genre, publisher, developer, critic_score, total_sales, na_sales, jp_sales, pal_sales, other_sales, release_date]
Index: []

In [95]:
df.to_csv('vgchartz_cleaned(Pandas).csv', index=False)